apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-kube-scheduler
  name: deployment-kube-scheduler-config
data:
  config.yaml: |
    apiVersion: componentconfig/v1alpha1
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: /etc/kubernetes/static-pod-resources/secrets/scheduler-kubeconfig/kubeconfig
