apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    tier: "control-plane"
    k8s-app: "kube-scheduler"
    openshift.io/control-plane: "true"
    openshift.io/component: "scheduler"
  annotations:
    openshift.io/run-level: "0"
spec:
  selector:
    matchLabels:
      tier: "control-plane"
      k8s-app: "kube-scheduler"
      openshift.io/control-plane: "true"
      openshift.io/component: "scheduler"
  template:
    metadata:
      labels:
        tier: "control-plane"
        k8s-app: "kube-scheduler"
        openshift.io/control-plane: "true"
        openshift.io/component: "scheduler"
    spec:
      containers:
      - name: kube-scheduler
        image: {{ .Image }}
        imagePullPolicy: {{ .ImagePullPolicy }}
        command: ["hyperkube", "kube-scheduler"]
        args:
        - --leader-elect=true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
