apiVersion: v1
kind: Secret
metadata:
  name: scheduler-kubeconfig
  namespace: openshift-kube-scheduler
  labels:
    tier: "control-plane"
    k8s-app: "kube-scheduler"
    openshift.io/control-plane: "true"
    openshift.io/component: "scheduler"
data:
  kubeconfig: {{ .Assets | load "kubeconfig" | base64 }}
